server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: task-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true
    username: root
    password: asease22

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  task:
    name: TaskQueue