server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: task-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/task?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  keycloak:
    realm: ${KEYCLOAK_REALM}
    auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
    client-id: ${KEYCLOAK_CLIENT_ID}
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET}

queue:
  task:
    name: TaskQueue
